dd if=/dev/zero of=upload_test bs=1000000 count=1000
mkdir test
touch test/test0.txt
touch test/test1.txt
touch test/test2.txt
touch test/test3.txt
touch test/test4.txt
touch test/test5.txt
touch test/test6.txt
touch test/test7.txt
touch test/test8.txt
touch test/test9.txt
touch test/test10.txt
touch test/test11.txt
touch test/test12.txt
touch test/test13.txt
touch test/test14.txt
touch test/test15.txt
touch test/test16.txt
touch test/test17.txt
touch test/test18.txt
touch test/test19.txt
touch test/test20.txt
touch test/test21.txt
touch test/test22.txt
touch test/test23.txt
touch test/test24.txt
touch test/test25.txt
touch test/test26.txt
touch test/test27.txt
touch test/test28.txt
touch test/test29.txt
touch test/test30.txt
touch test/test31.txt
touch test/test32.txt
touch test/test33.txt
touch test/test34.txt
touch test/test35.txt
touch test/test36.txt
touch test/test37.txt
touch test/test38.txt
touch test/test39.txt
touch test/test40.txt
touch test/test41.txt
touch test/test42.txt
touch test/test43.txt
touch test/test44.txt
touch test/test45.txt
touch test/test46.txt
touch test/test47.txt
touch test/test48.txt
touch test/test49.txt
